"""Execution environment protocol shared by Local and Docker backends."""

from __future__ import annotations

from typing import Protocol

from .models import ExecRequest, ExecResult


class ExecutionEnvironment(Protocol):
    workspace_root: object

    async def read_file(self, file_path: str) -> str: ...
    async def write_file(self, file_path: str, content: str) -> str: ...
    async def edit_file(self, file_path: str, old_string: str, new_string: str) -> str: ...
    async def list_files(self, pattern: str, path: str = ".") -> str: ...
    async def search(self, pattern: str, path: str = ".", include: str | None = None) -> str: ...
    def shell_argv(self, command: str) -> tuple[str, ...]: ...
    async def exec(self, request: ExecRequest) -> ExecResult: ...
    async def diff(self) -> str: ...
    async def close(self) -> None: ...
